name: sequenzautils_seqzbinning
description: Sequenza-utils seqzbinning postprocess a seqz file into a smaller binned seqz file
keywords:
  - sequenzautils
  - copy number
  - seqzbinning
tools:
  - sequenzautils:
      description: Sequenza-utils provides 3 main command line programs to transform common NGS file format - such as FASTA, BAM - to input files for the Sequenza R package. The program - bam2seqz - process a paired set of BAM/pileup files (tumour and matching normal), and GC-content genome-wide information, to extract the common positions with A and B alleles frequencies.
      homepage: https://sequenza-utils.readthedocs.io/en/latest/index.html
      documentation: https://sequenza-utils.readthedocs.io/en/latest/index.html
      doi: 10.1093/annonc/mdu479
      licence: ["GPL-3.0-or-later"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - seqz:
      type: file
      description: Seqz file
      pattern: "*.{seqz.gz}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - seqz:
      type: file
      description: Seqz file
      pattern: "*.{seqz.binned.gz}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@priesgo"
  - "@JulianMohr"
  